server:
  port: 1000
spring:
  datasource:
    url: jdbc:mysql://****:3306/greencity?serverTimezone=GMT+8&useUnicode=true&characterEncoding=utf8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.greencity.website.mapper.*: DEBUG