server:
  port: 1001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/greencity?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.greencity.website.mapper.*: DEBUG